% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Apr-2026 07:57:40
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('soal_2_invers_citra.mat');

D = [26 32 38 44 55 61 67];

D_sort = [26 32 38 44 55 61 67];

K = 7;

N = 6;

a = 0;

alpha_lr = 0.007;

b = 6;

bar_h = saveVarsMat.bar_h; % <1x1 matlab.graphics.chart.primitive.Bar> unsupported class

dev = 20.857142857142854;

dev_sq = 435.02040816326519;

has_mode = false;

i = 7;

idx_bergejolak = 7;

idx_konsisten = 4;

jarak = [20.142857142857146 14.142857142857146 8.1428571428571459 2.1428571428571459 ...
         8.8571428571428541 14.857142857142854 20.857142857142854];

mean_D = 46.142857142857146;

median_D = 44;

mode_D = 26;

range_D = 41;

std_D_pop = 14.196866570062678;

sum_sq = 1410.8571428571427;

tanda = ' ← paling bergejolak';

theta0 = 30;

uniq_vals = [26 32 38 44 55 61 67];

v = 67;

var_D_pop = 201.55102040816323;

clear saveVarsMat;
